export let aniData = {
    "id": "",
    "url": "",
    "standbyRssList": [],
    "title": "",
    "offset": 0,
    "year": 2025,
    "month": 4,
    "date": 8,
    "week": 2,
    "season": 1,
    "cover": "",
    "image": "",
    "subgroup": "LoliHouse",
    "match": [],
    "exclude": [
        "720[Pp]",
        "\\d-\\d",
        "合集",
        "特别篇"
    ],
    "globalExclude": true,
    "ova": false,
    "pinyin": "",
    "enable": true,
    "currentEpisodeNumber": 10,
    "totalEpisodeNumber": 12,
    "themoviedbName": "",
    "type": "mikan",
    "bgmUrl": "",
    "customDownloadPath": false,
    "downloadPath": "",
    "score": 8,
    "customEpisode": false,
    "customEpisodeStr": "",
    "customEpisodeGroupIndex": 0,
    "omit": true,
    "downloadNew": false,
    "notDownload": [],
    "tmdb": {
        "id": "0",
        "name": "",
        "date": "2025-01-01 00:00:00"
    },
    "upload": true,
    "procrastinating": true,
    "customRenameTemplateEnable": false,
    "customRenameTemplate": "[${subgroup}] ${title} S${seasonFormat}E${episodeFormat}",
    "lastDownloadTime": 0,
    "message": true
}
