export let configData = {
    "mikanHost": "https://mikanime.tv",
    "tmdbApi": "https://api.themoviedb.org",
    "tmdbApiKey": "",
    "tmdbAnime": true,
    "downloadToolType": "qBittorrent",
    "downloadRetry": 3,
    "downloadToolHost": "",
    "downloadToolUsername": "",
    "downloadToolPassword": "",
    "qbUseDownloadPath": false,
    "ratioLimit": -2,
    "seedingTimeLimit": -2,
    "inactiveSeedingTimeLimit": -2,
    "downloadPathTemplate": "/Users/wushuo/Movies/番剧/${letter}/${title}/Season ${season}",
    "ovaDownloadPathTemplate": "/Users/wushuo/Movies/剧场版/${letter}/${title}",
    "watchErrorTorrent": true,
    "customTags": [],
    "delayedDownload": 0,
    "scoreShow": true,
    "sleep": 15,
    "renameSleepSeconds": 10,
    "gcSleep": 10,
    "rename": true,
    "rss": true,
    "rssTimeout": 20,
    "fileExist": false,
    "awaitStalledUP": true,
    "delete": false,
    "deleteStandbyRSSOnly": false,
    "deleteFiles": false,
    "offset": false,
    "titleYear": false,
    "autoDisabled": false,
    "skip5": true,
    "standbyRss": false,
    "coexist": false,
    "logsMax": 2048,
    "debug": false,
    "proxy": false,
    "proxyList": "",
    "proxyHost": "",
    "proxyPort": 8080,
    "proxyUsername": "",
    "proxyPassword": "",
    "downloadCount": 0,
    "login": {
        "username": "admin",
        "password": ""
    },
    "multiLoginForbidden": true,
    "loginEffectiveHours": 3,
    "exclude": [
        "720[Pp]",
        "\\d-\\d",
        "合集",
        "特别篇"
    ],
    "importExclude": false,
    "enabledExclude": false,
    "bgmJpName": false,
    "tmdb": false,
    "tmdbId": false,
    "tmdbIdPlexMode": false,
    "tmdbLanguage": "zh-CN",
    "tmdbRomaji": false,
    "ipWhitelist": false,
    "ipWhitelistStr": "",
    "showPlaylist": true,
    "omit": true,
    "bgmToken": "",
    "apiKey": "",
    "weekShow": true,
    "downloadNew": false,
    "innerIP": false,
    "renameTemplate": "[${subgroup}] ${title} S${seasonFormat}E${episodeFormat}",
    "renameDelYear": false,
    "renameDelTmdbId": false,
    "maxFileNameLength": 0,
    "verifyLoginIp": false,
    "autoTrackersUpdate": false,
    "trackersUpdateUrls": "https://cf.trackerslist.com/best.txt",
    "notificationTemplate": "",
    "autoUpdate": false,
    "alistHost": "",
    "alistToken": "",
    "alistPath": "/115/Media/番剧/${letter}/${title}/Season ${season}",
    "alistOvaPath": "/115/Media/剧场版/${letter}/${title}",
    "alist": false,
    "alistRetry": 5,
    "alistTask": true,
    "version": "",
    "bgmImage": "large",
    "customCss": "",
    "customJs": "",
    "customEpisode": false,
    "customEpisodeStr": "",
    "customEpisodeGroupIndex": 0,
    "provider": "115 Cloud",
    "upload": true,
    "upLimit": 0,
    "dlLimit": 0,
    "expirationTime": 0,
    "outTradeNo": "",
    "verifyExpirationTime": false,
    "tryOut": false,
    "procrastinating": false,
    "procrastinatingDay": 14,
    "github": "None",
    "customGithub": false,
    "customGithubUrl": "",
    "githubToken": "",
    "alistRefresh": false,
    "alistRefreshDelayed": 0,
    "updateTotalEpisodeNumber": false,
    "forceUpdateTotalEpisodeNumber": false,
    "alistDownloadTimeout": 60,
    "alistDownloadRetryNumber": 5,
    "tvShowNfo": false,
    "configBackup": false,
    "configBackupDay": 7,
    "showLastDownloadTime": false,
    "completed": false,
    "completedPathTemplate": "/Users/wushuo/Movies/已完结番剧/${letter}/${title}/Season ${season}",
    "notificationConfigList": [],
    "priorityKeywordsEnable": false,
    "priorityKeywords": [],
    "procrastinatingMasterOnly": true,
    "limitLoginAttempts": true,
    "buildInfo": ''
}
