#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HttpMethod {
    Get,
    Post,
}

#[derive(Debug, Clone, Copy)]
pub struct EndpointDef {
    pub key: &'static str,
    pub group: &'static str,
    pub path: &'static str,
    pub method: HttpMethod,
    pub multipart: bool,
    pub binary: bool,
    pub description: &'static str,
}

pub const ENDPOINTS: &[EndpointDef] = &[
    EndpointDef {
        key: "config",
        group: "config",
        path: "/api/config",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get current Ani-RSS config",
    },
    EndpointDef {
        key: "setConfig",
        group: "config",
        path: "/api/setConfig",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Update Ani-RSS config",
    },
    EndpointDef {
        key: "clearCache",
        group: "config",
        path: "/api/clearCache",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Clear runtime cache",
    },
    EndpointDef {
        key: "trackersUpdate",
        group: "config",
        path: "/api/trackersUpdate",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Refresh trackers from config",
    },
    EndpointDef {
        key: "testProxy",
        group: "config",
        path: "/api/testProxy",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Test configured proxy",
    },
    EndpointDef {
        key: "downloadLoginTest",
        group: "config",
        path: "/api/downloadLoginTest",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Validate downloader login",
    },
    EndpointDef {
        key: "customJs",
        group: "config",
        path: "/api/custom.js",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Fetch custom JavaScript",
    },
    EndpointDef {
        key: "customCss",
        group: "config",
        path: "/api/custom.css",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Fetch custom CSS",
    },
    EndpointDef {
        key: "exportConfig",
        group: "config",
        path: "/api/exportConfig",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Export configuration archive",
    },
    EndpointDef {
        key: "importConfig",
        group: "config",
        path: "/api/importConfig",
        method: HttpMethod::Post,
        multipart: true,
        binary: false,
        description: "Import configuration archive",
    },
    EndpointDef {
        key: "listAni",
        group: "anime",
        path: "/api/listAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "List subscriptions",
    },
    EndpointDef {
        key: "addAni",
        group: "anime",
        path: "/api/addAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Create subscription",
    },
    EndpointDef {
        key: "setAni",
        group: "anime",
        path: "/api/setAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Update subscription",
    },
    EndpointDef {
        key: "deleteAni",
        group: "anime",
        path: "/api/deleteAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Delete subscriptions",
    },
    EndpointDef {
        key: "updateTotalEpisodeNumber",
        group: "anime",
        path: "/api/updateTotalEpisodeNumber",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Refresh episode totals",
    },
    EndpointDef {
        key: "batchEnable",
        group: "anime",
        path: "/api/batchEnable",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Batch enable or disable subscriptions",
    },
    EndpointDef {
        key: "refreshAll",
        group: "anime",
        path: "/api/refreshAll",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Refresh all subscriptions",
    },
    EndpointDef {
        key: "refreshAni",
        group: "anime",
        path: "/api/refreshAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Refresh one subscription",
    },
    EndpointDef {
        key: "rssToAni",
        group: "anime",
        path: "/api/rssToAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Convert RSS payload to Ani object",
    },
    EndpointDef {
        key: "previewAni",
        group: "anime",
        path: "/api/previewAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Preview matching results",
    },
    EndpointDef {
        key: "downloadPath",
        group: "anime",
        path: "/api/downloadPath",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Resolve download path",
    },
    EndpointDef {
        key: "importAni",
        group: "anime",
        path: "/api/importAni",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Import subscriptions",
    },
    EndpointDef {
        key: "refreshCover",
        group: "anime",
        path: "/api/refreshCover",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Refresh cover for one subscription",
    },
    EndpointDef {
        key: "mikan",
        group: "search",
        path: "/api/mikan",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Search Mikan",
    },
    EndpointDef {
        key: "mikanGroup",
        group: "search",
        path: "/api/mikanGroup",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Fetch Mikan subgroup list",
    },
    EndpointDef {
        key: "mikanCover",
        group: "search",
        path: "/api/mikanCover",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Fetch Mikan cover image",
    },
    EndpointDef {
        key: "getThemoviedbName",
        group: "search",
        path: "/api/getThemoviedbName",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Resolve TMDB title",
    },
    EndpointDef {
        key: "getThemoviedbGroup",
        group: "search",
        path: "/api/getThemoviedbGroup",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Fetch TMDB episode groups",
    },
    EndpointDef {
        key: "searchBgm",
        group: "bgm",
        path: "/api/searchBgm",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Search Bangumi subject",
    },
    EndpointDef {
        key: "getAniBySubjectId",
        group: "bgm",
        path: "/api/getAniBySubjectId",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Convert Bangumi subject to Ani object",
    },
    EndpointDef {
        key: "getBgmTitle",
        group: "bgm",
        path: "/api/getBgmTitle",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get Bangumi title",
    },
    EndpointDef {
        key: "rate",
        group: "bgm",
        path: "/api/rate",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Read Bangumi rating",
    },
    EndpointDef {
        key: "setRate",
        group: "bgm",
        path: "/api/setRate",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Submit Bangumi rating",
    },
    EndpointDef {
        key: "meBgm",
        group: "bgm",
        path: "/api/meBgm",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get Bangumi account details",
    },
    EndpointDef {
        key: "bgmOauthCallback",
        group: "bgm",
        path: "/api/bgm/oauth/callback",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Submit Bangumi OAuth callback code",
    },
    EndpointDef {
        key: "playList",
        group: "play",
        path: "/api/playList",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get playlist entries",
    },
    EndpointDef {
        key: "getSubtitles",
        group: "play",
        path: "/api/getSubtitles",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Read embedded subtitles",
    },
    EndpointDef {
        key: "startCollection",
        group: "play",
        path: "/api/startCollection",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Start collection download",
    },
    EndpointDef {
        key: "previewCollection",
        group: "play",
        path: "/api/previewCollection",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Preview collection file tree",
    },
    EndpointDef {
        key: "getCollectionSubgroup",
        group: "play",
        path: "/api/getCollectionSubgroup",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Resolve collection subgroup",
    },
    EndpointDef {
        key: "torrentsInfos",
        group: "download",
        path: "/api/torrentsInfos",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "List torrents info",
    },
    EndpointDef {
        key: "deleteTorrent",
        group: "download",
        path: "/api/deleteTorrent",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Delete cached torrent metadata",
    },
    EndpointDef {
        key: "testNotification",
        group: "notification",
        path: "/api/testNotification",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Test a notification config",
    },
    EndpointDef {
        key: "newNotification",
        group: "notification",
        path: "/api/newNotification",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Create default notification config",
    },
    EndpointDef {
        key: "getTgUpdates",
        group: "notification",
        path: "/api/getTgUpdates",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Read Telegram updates",
    },
    EndpointDef {
        key: "logs",
        group: "logs",
        path: "/api/logs",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get runtime logs",
    },
    EndpointDef {
        key: "clearLogs",
        group: "logs",
        path: "/api/clearLogs",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Clear runtime logs",
    },
    EndpointDef {
        key: "downloadLogs",
        group: "logs",
        path: "/api/downloadLogs",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Download log archive",
    },
    EndpointDef {
        key: "scrape",
        group: "metadata",
        path: "/api/scrape",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Trigger metadata scrape",
    },
    EndpointDef {
        key: "getEmbyViews",
        group: "emby",
        path: "/api/getEmbyViews",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "List Emby libraries",
    },
    EndpointDef {
        key: "embyWebHook",
        group: "emby",
        path: "/api/embyWebHook",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Trigger Emby webhook handler",
    },
    EndpointDef {
        key: "about",
        group: "system",
        path: "/api/about",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Get app information",
    },
    EndpointDef {
        key: "update",
        group: "system",
        path: "/api/update",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Trigger update routine",
    },
    EndpointDef {
        key: "stop",
        group: "system",
        path: "/api/stop",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Restart or stop service",
    },
    EndpointDef {
        key: "file",
        group: "files",
        path: "/api/file",
        method: HttpMethod::Get,
        multipart: false,
        binary: true,
        description: "Download local file",
    },
    EndpointDef {
        key: "upload",
        group: "files",
        path: "/api/upload",
        method: HttpMethod::Post,
        multipart: true,
        binary: false,
        description: "Upload one file",
    },
    EndpointDef {
        key: "verifyNo",
        group: "afdian",
        path: "/api/verifyNo",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Verify Afdian order number",
    },
    EndpointDef {
        key: "tryOut",
        group: "afdian",
        path: "/api/tryOut",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Request trial",
    },
    EndpointDef {
        key: "login",
        group: "auth",
        path: "/api/login",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Login and obtain Authorization token",
    },
    EndpointDef {
        key: "testIpWhitelist",
        group: "auth",
        path: "/api/testIpWhitelist",
        method: HttpMethod::Post,
        multipart: false,
        binary: false,
        description: "Check IP whitelist login path",
    },
];

pub fn endpoint_by_key(key: &str) -> Option<&'static EndpointDef> {
    ENDPOINTS.iter().find(|endpoint| endpoint.key.eq_ignore_ascii_case(key))
}
